#!/usr/bin/perl

#Author: Ryan Bullock
#Version: 0.2
#Description: This provided a very simple command server for the asterisk manager interface.

use strict;
use warnings;

use Getopt::Long;

GetOptions(
    "help"    => \&usage,
    "start"   => \&run,
    "status"  => \&status,
    "stop"    => \&stop,
    "byoptions"    => \&byoptions
    ) or &byoptions;

#print $pf."+".$pid."\n";
#sleep(100);
#AnyEvent::Impl::Perl::loop;
#&byoptions;
exit(0);
# ==================================================
sub usage
{
    my ($opt_name, $opt_value) = @_;
    print "your usage text goes here...\n";
    exit(0);
}
# ==================================================
sub reload
{
    my ($opt_name, $opt_value) = @_;
    print "reload process not implemented.\n";
}
# ==================================================
sub restart
{
    my ($opt_name, $opt_value) = @_;
    &stop;
    &run;
}
# ==================================================
sub stop {
	print `/usr/local/sbin/agitask -stop`;
	print `/usr/local/sbin/atsrobot -stop`;
}

sub status {
	print `/usr/local/sbin/agitask -status`;
	print `/usr/local/sbin/atsrobot -status`;
}

sub run {
	print `/usr/local/sbin/agitask -start`;
	print `/usr/local/sbin/atsrobot -start`;
}

sub byoptions {
	use DBI;
	# имя базы данных
	my $dbname = "asterisk";
	# имя пользователя
	my $username = "asterisk";
	# пароль
	#my $password = "AstraKonESTIk98";
	my $password = "asteposter54gy";
	# имя или IP адрес сервера
	my $dbhost = "localhost";
	# порт
	my $dbport = "5432";
	# опции
	my $dboptions = "-e";
	# терминал
	my $dbtty = "ansi";

	my $robottablename = 'callrobot';

	my $queryupdate;
	my $rvupdate;

	my $dbh = DBI->connect("dbi:Pg:dbname=$dbname;host=$dbhost;port=$dbport;options=$dboptions;tty=$dbtty","$username","$password",
			    {PrintError => 0});
	my $query = "SELECT optval FROM atsoptions WHERE optname = 'WORKROBOT'";

	my $sth = $dbh->prepare($query);
	my $rv;
	my @array = ();
	$rv = $sth->execute();
	@array = $sth->fetchrow_array();
	if($array[0] eq 'YES') {
		&run();
	} else {
		&stop();
	}
}
